# Generated by Django 4.1.3 on 2022-11-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetsTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=60)),
                ('company_email', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reviewsss',
            name='linkedin',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewsss',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewsss',
            name='priority',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reviewsss',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
