# Generated by Django 4.0.4 on 2022-11-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsss',
            name='turnonn',
            field=models.BooleanField(default=False),
        ),
    ]
