# Generated by Django 3.2.1 on 2023-07-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_letstalk_alter_reviewsss_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsss',
            name='linkedin',
            field=models.TextField(),
        ),
    ]
